resource_group_id     = "/subscriptions/d79627b1-6f38-4296-92ae-6de3c9d881a4/resourceGroups/cglabs-azfuncdemo"
managed_identity_name = "cglabs-azfuncdemo-identity"
storage_account_name  = "cglabsazfuncdemodrop"
container_name        = "filedrop"
app_service_plan_name = "cglabs-azfuncdemo-asp"
