name: Deploy FunctionAppDemo

on:
  push:
    branches: ["main"]

jobs:

## Deploy Infrastructure
  terraform:
    name: Execute Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init
        working-directory: infra/

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: infra/

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var-file="terraform.tfvars" -out=tfplan
        working-directory: infra/
        
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve $TF_PLAN_PATH
        working-directory: infra/

      - name: Collect Terraform Outputs and Save as Artifact
        id: save_outputs
        run: |
          terraform output -json > terraform-outputs.json 2>/dev/null
        working-directory: infra/

      - name: Upload Terraform Outputs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: infra/terraform-outputs.json

## Deploy Azure Functions 
  deploy_functions:
    name: Deploy Azure Functions
    runs-on: ubuntu-latest
    needs: terraform

    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions/.'       
      FUNCTION_APP_PACKAGE_NAME: 'functionapp.zip'  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Terraform Outputs Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: .

      - name: Debug Terraform Outputs
        run: cat terraform-outputs.json

      - name: Parse Terraform Outputs
        shell: bash
        run: |
           FUNCTION_APP_NAME=$(cat terraform-outputs.json | jq -r '.FunctionAppName.value')
           FUNC_RESOURCE_GROUP=$(cat terraform-outputs.json | jq -r '.resource_group_name.value')

      - name: Verify Variables
        shell: bash
        run: |
          echo $FUNCTION_APP_NAME
          echo $FUNC_RESOURCE_GROUP
          echo $AZURE_FUNCTIONAPP_PACKAGE_PATH
          echo $FUNCTION_APP_PACKAGE_NAME

      - name: Log in to Azures
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip Function App Contents
        run: |
          zip -r $FUNCTION_APP_PACKAGE_NAME $AZURE_FUNCTIONAPP_PACKAGE_PATH
