name: Deploy Azure Functions

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions/.'       
  FUNCTION_APP_PACKAGE_NAME: 'functionapp.zip'  

on:
  workflow_run:
    workflows:
      - Deploy Infrastructure with Terraform
    types:
      - completed

jobs:
  deploy:
    name: Deploy Azure Functions
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_commit.message, 'functions/')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Function App Name from Terraform Output
        id: get_functionapp_name
        run: |
          FUNCTION_APP_NAME=$(terraform output -raw FunctionAppName)
          FUNC_RESOURCE_GROUP=$(terraform output -raw resource_group_name)
          echo "FUNCTION_APP_NAME=$FUNCTION_APP_NAME" >> $GITHUB_ENV
        working-directory: infra/
        
      - name: Zip Function App Contents
        run: |
          zip -r $FUNCTION_APP_PACKAGE_NAME $AZURE_FUNCTIONAPP_PACKAGE_PATH

      - name: Publish Azure Function
        run: |
          az functionapp deployment source config-zip \
            --name ${{ vars.FUNCTION_APP_NAME }} \
            --resource-group ${{ vars.FUNC_RESOURCE_GROUP }} \
            --src $FUNCTION_APP_PACKAGE_NAME
