name: Deploy Infrastructure with Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/deploy_infra.yml'
  pull_request:
    paths:
      - 'infra/**'

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init
        working-directory: infra/

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: infra/

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var-file="terraform.tfvars" -out=tfplan
        working-directory: infra/

      - name: Save Plan Output
        run: echo "TF_PLAN_PATH=tfplan" >> $GITHUB_ENV

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false -auto-approve $TF_PLAN_PATH
        working-directory: infra/