name: Deploy Azure Functions

env:
  AZURE_FUNCTIONAPP_NAME: 'functions'       # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions/.'       # set this to the path to your function app project, defaults to the repository root


on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'
      - '.github/workflows/deploy_functions.yml'


jobs:
    deploy:
        name: Deploy Azure Functions
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Deploy Functions
              uses: Azure/functions-action@v1
              id: fa
              with:
                app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
                package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
                publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
       
            
