name: Deploy Azure Functions

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions/.'       
  FUNCTION_APP_PACKAGE_NAME: 'functionapp.zip'  

on:
  workflow_run:
    workflows: ["Deploy Infrastructure with Terraform"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Azure Functions
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Terraform Outputs Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          run-id: ${{ github.event.workflow_run.id }}

      - name: Parse Terraform Outputs
        id: parse_outputs
        run: |
          FUNCTION_APP_NAME=$(jq -r '.FunctionAppName.value' terraform-outputs.json)
          FUNC_RESOURCE_GROUP=$(jq -r '.resource_group_name.value' terraform-outputs.json)
          echo "FUNCTION_APP_NAME=$FUNCTION_APP_NAME" >> $GITHUB_ENV
          echo "FUNC_RESOURCE_GROUP=$FUNC_RESOURCE_GROUP" >> $GITHUB_ENV

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip Function App Contents
        run: |
          zip -r $FUNCTION_APP_PACKAGE_NAME $AZURE_FUNCTIONAPP_PACKAGE_PATH

      - name: Publish Azure Function
        run: |
          az functionapp deployment source config-zip \
            --name $FUNCTION_APP_NAME \
            --resource-group $FUNC_RESOURCE_GROUP \
            --src $FUNCTION_APP_PACKAGE_NAME