name: Deploy FunctionAppDemo

on:
  push:
    branches: ["main"]

jobs:

## Deploy Infrastructure
  terraform:
    name: Execute Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init
        working-directory: infra/

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: infra/

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var-file="terraform.tfvars" -out=tfplan
        working-directory: infra/
        
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
        working-directory: infra/

      - name: Save Clean Terraform Outputs
        shell: bash
        run: |
          bash -c "terraform output -json" > terraform-outputs.json
          awk 'BEGIN{p=0} /^\{/ {p=1} p' terraform-outputs.json > clean.json
          mv clean.json terraform-outputs.json
        working-directory: infra/

      - name: Upload Terraform Outputs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: infra/terraform-outputs.json

## Deploy Azure Functions 
  deploy_functions:
    name: Deploy Azure Functions
    runs-on: ubuntu-latest
    needs: terraform

    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'functions/.'       
      FUNCTION_APP_PACKAGE_NAME: 'functionapp.zip'  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Terraform Outputs Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: .

      - name: Debug Terraform Outputs
        run: cat terraform-outputs.json

      - name: Parse Terraform Outputs
        shell: bash
        run: |
          FUNCTION_APP_NAME=$(jq -r '.FunctionAppName.value' terraform-outputs.json)
          FUNC_RESOURCE_GROUP=$(jq -r '.resource_group_name.value' terraform-outputs.json)

          echo "FUNCTION_APP_NAME=$FUNCTION_APP_NAME" >> $GITHUB_ENV
          echo "FUNC_RESOURCE_GROUP=$FUNC_RESOURCE_GROUP" >> $GITHUB_ENV

      - name: Verify Variables
        shell: bash
        run: |
          echo $FUNCTION_APP_NAME
          echo $FUNC_RESOURCE_GROUP
          echo $AZURE_FUNCTIONAPP_PACKAGE_PATH
          echo $FUNCTION_APP_PACKAGE_NAME

      - name: Log in to Azures
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Zip Function App Contents
        run: |
          zip -r $FUNCTION_APP_PACKAGE_NAME $AZURE_FUNCTIONAPP_PACKAGE_PATH
