name: Deploy Infrastructure with Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - .github/workflows/deploy-infra.yml
  pull_request:

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init
        working-directory: infra/

      - name: Terraform Validate
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform validate
        working-directory: infra/
    
      - name: Terraform Format
        run: terraform fmt -check
        working-directory: infra/

      - name: Terraform Plan
        run: terraform plan -input=false -var-file="terraform.tfvars"
        working-directory: infra/

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file="terraform.tfvars"
        working-directory: infra/