name: Validate Terraform

on:
  pull_request:
    branches: ["main"]
    paths:
      - '.github/workflows/merge_check.yml'
      - 'infra/**'

jobs:
  terraform:
    name: Verify Terraform Configurations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        run: terraform init
        working-directory: infra/

      - name: Terraform Validateclear
        run: terraform validate
        working-directory: infra/

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: infra/

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var-file="terraform.tfvars" 
        working-directory: infra/

